### PR TITLE
Changed double type by BigDecimal to better manage decimals.

### PR DESCRIPTION
**Pull request by xaldama**
Comparing the resulting scores with the score calculator published by (first.org)[https://www.first.org/cvss/calculator/cvsscalc40], there are some discrepancies.
Some of them are because a js limitations working with decimal (this library is more precise).
But there are some other cases that differs because a precision loose when the score is being calculated.

In cases like the following one related to the vector  CVSS:4.0/AV:P/AC:L/AT:P/PR:L/UI:P/VC:H/VI:H/VA:H/SC:H/SI:L/SA:H/E:U/CR:L/IR:H/AR:L/MAV:P/MAC:H/MAT:P/MPR:L/MUI:P/MVC:H/MVI:H/MVA:L/MSI:H/MSA:H/S:P/AU:Y/R:A/V:D/RE:L/U:Red
is resolved as 

- **using double**
    4.1 - 0,7499999999999999 = 3.3499999999999996
 
- **using BigDecimal**
    4.1 - 0.74999999999999989 = 3.3500000000000001

So, using double the score calculation end with 3.3 when it really is 3.4.
Using BigDecimal the score is 3.4.

### CODE REVIEW

**Comment by YanWittmann** [comment]
Hey there!

First of all: Fantastic catch! When I first saw your PR just now, I could not believe my eyes. But, you're actually correct.

I can't believe something this big went past me when implementing the library. I would have bet that I generated the test dataset using the reference implementation, I can't believe that this is was not actually the case.

I checked your implementation and it looks good to me. There are also no performance differences to the original double implementation.

While testing this out, I noticed that our TypeScript implementation has the same issue. I will check if the issue is of similar nature there (most likely) and then come back to this one.

Thank you!

**Comment by YanWittmann** [comment]
Okay... I just tested with some more vectors, and I get 0.6 for this vector using the BigDecimal implementation:

CVSS:4.0/AV:L/AC:H/AT:P/PR:H/UI:A/VC:L/VI:L/VA:L/SC:L/SI:H/SA:L/E:U/CR:L/IR:M/AR:L/MAV:L/MAC:L/MAT:P/MPR:L/MUI:A/MVC:H/MVI:H/MVA:L/MSC:L/MSI:L/MSA:L/S:P/AU:Y/R:I/V:C/RE:L/U:Clear

But the official implementation returns 0.7.
This is what the double implementation also returns.

I'll investigate further.

**Comment by YanWittmann** [comment]
I think these are the vectors your implementation still calculates incorrectly:

```
CVSS:4.0/AV:L/AC:H/AT:P/PR:H/UI:A/VC:L/VI:L/VA:L/SC:L/SI:H/SA:L/E:U/CR:L/IR:M/AR:L/MAV:L/MAC:L/MAT:P/MPR:L/MUI:A/MVC:H/MVI:H/MVA:L/MSC:L/MSI:L/MSA:L/S:P/AU:Y/R:I/V:C/RE:L/U:Clear 210221 0.7
CVSS:4.0/AV:L/AC:H/AT:P/PR:L/UI:A/VC:L/VI:H/VA:L/SC:H/SI:L/SA:L/E:U/CR:L/IR:M/AR:L/MAV:P/MAC:L/MAT:P/MPR:L/MUI:P/MVC:H/MVI:H/MVA:L/MSC:L/MSI:L/MSA:L/S:P/AU:Y/R:U/V:C/RE:L/U:Clear 210221 0.7
CVSS:4.0/AV:P/AC:H/AT:P/PR:H/UI:A/VC:H/VI:H/VA:H/SC:L/SI:H/SA:L/E:A/CR:L/IR:H/AR:L/MAV:P/MAC:H/MAT:P/MPR:H/MUI:P/MVC:L/MVI:H/MVA:L/MSI:L/MSA:S/S:P/AU:Y/R:I/V:D/RE:L/U:Green 211000 6.9
CVSS:4.0/AV:A/AC:L/AT:P/PR:L/UI:A/VC:H/VI:L/VA:L/SC:L/SI:L/SA:H/E:P/CR:L/IR:L/MAC:L/MAT:N/MPR:N/MUI:N/MVI:L/MVA:H/MSC:N/MSI:S/AU:N/R:A/U:Red 101010 8.6
CVSS:4.0/AV:A/AC:H/AT:P/PR:H/UI:P/VC:L/VI:H/VA:H/SC:H/SI:L/SA:L/AR:L/MAV:P/MVC:N/MVA:N/MSC:N/MSI:H/MSA:S/R:A/V:D/RE:H/U:Green 211000 6.9
CVSS:4.0/AV:L/AC:H/AT:P/PR:L/UI:A/VC:H/VI:H/VA:L/SC:L/SI:L/SA:L/E:U/CR:H/IR:H/AR:M/MAV:P/MPR:H/MVC:H/MVI:L/MSC:L/MSI:L/S:N/AU:N/R:A/RE:L/U:Green 211220 0.7
CVSS:4.0/AV:P/AC:L/AT:P/PR:H/UI:P/VC:H/VI:H/VA:H/SC:L/SI:H/SA:H/E:A/CR:H/AR:L/MAV:A/MAT:P/MUI:P/MVC:H/MVI:N/MVA:N/MSI:L/MSA:S/S:P/AU:N/V:D/RE:L/U:Clear 211000 6.9
CVSS:4.0/AV:A/AC:H/AT:P/PR:L/UI:P/VC:L/VI:H/VA:L/SC:L/SI:L/SA:H/CR:L/IR:L/MAV:P/MAC:H/MPR:N/MUI:N/MVI:L/MVA:H/MSC:L/MSI:S/MSA:L/S:N/AU:N/R:I/RE:H/U:Clear 211000 6.9
CVSS:4.0/AV:L/AC:L/AT:P/PR:H/UI:P/VC:H/VI:L/VA:L/SC:H/SI:L/SA:H/E:U/CR:H/IR:H/AR:M/MAV:P/MPR:L/MUI:A/MVC:H/MVA:L/MSC:N/MSA:L/S:N/AU:Y/R:I/V:D/RE:H/U:Green 211220 0.7
CVSS:4.0/AV:A/AC:H/AT:P/PR:H/UI:A/VC:H/VI:L/VA:L/SC:L/SI:H/SA:L/E:A/IR:L/AR:L/MAV:L/MAT:N/MPR:L/MUI:A/MVI:L/MVA:L/MSC:L/MSI:L/MSA:S/S:N/AU:Y/R:I/V:C/RE:M/U:Red 211000 6.9
CVSS:4.0/AV:A/AC:L/AT:P/PR:L/UI:P/VC:H/VI:L/VA:L/SC:L/SI:H/SA:L/E:U/CR:H/IR:H/MAV:L/MPR:L/MUI:P/MVI:N/MSC:N/MSI:N/MSA:L/V:C/U:Clear 211220 0.7
CVSS:4.0/AV:A/AC:H/AT:P/PR:H/UI:P/VC:L/VI:H/VA:H/SC:L/SI:L/SA:L/E:U/CR:M/IR:L/AR:M/MAV:P/MAC:H/MVC:H/MVA:H/MSA:L/AU:Y/R:I/RE:H 210221 1.0
CVSS:4.0/AV:P/AC:H/AT:P/PR:H/UI:A/VC:H/VI:L/VA:L/SC:H/SI:H/SA:H/E:U/CR:L/IR:H/AR:L/MAV:A/MAC:H/MAT:N/MPR:H/MUI:N/MVC:L/MVI:H/MVA:L/MSC:H/MSI:S/MSA:S/S:N/AU:Y/R:U/RE:H/U:Red 111020 5.8
CVSS:4.0/AV:L/AC:L/AT:P/PR:L/UI:P/VC:H/VI:H/VA:L/SC:H/SI:L/SA:H/IR:M/AR:M/MAC:H/MPR:N/MUI:P/MVC:H/MVI:L/MVA:N/MSC:H/MSI:H/MSA:H/S:N/R:I/RE:M 111100 7.1
CVSS:4.0/AV:A/AC:H/AT:P/PR:L/UI:A/VC:L/VI:H/VA:L/SC:H/SI:H/SA:H/E:A/IR:L/MAV:P/MPR:N/MUI:P/MVC:H/MVI:N/MVA:N/MSC:H/MSI:S/MSA:N/S:N/AU:Y/V:D/RE:M/U:Green 211000 6.9
CVSS:4.0/AV:A/AC:H/AT:P/PR:H/UI:A/VC:L/VI:L/VA:L/SC:L/SI:L/SA:L/E:U/IR:M/AR:M/MAV:L/MAC:L/MPR:N/MUI:N/MVC:H/MVA:N/MSC:H/MSI:S/MSA:S/S:P/AU:Y/R:U/RE:M/U:Amber 111020 6.0
CVSS:4.0/AV:A/AC:H/AT:P/PR:L/UI:A/VC:L/VI:H/VA:H/SC:L/SI:L/SA:L/E:U/CR:L/IR:M/AR:M/MAV:P/MAC:H/MAT:P/MPR:H/MUI:N/MVC:H/MVI:H/MVA:H/MSA:N/S:P/R:A/RE:M 210221 1.0
CVSS:4.0/AV:A/AC:L/AT:P/PR:L/UI:A/VC:H/VI:H/VA:L/SC:L/SI:L/SA:H/E:U/CR:M/IR:L/AR:H/MAV:N/MAC:L/MAT:P/MPR:H/MVC:L/MVI:H/MSA:N/R:U/V:D/RE:M/U:Green 111221 1.0
CVSS:4.0/AV:A/AC:H/AT:P/PR:H/UI:P/VC:L/VI:H/VA:H/SC:L/SI:H/SA:H/CR:M/IR:L/AR:M/MAV:N/MAT:P/MPR:L/MUI:A/MVC:H/MVI:N/MVA:L/MSC:L/MSI:L/MSA:N/S:N/R:U/V:C/U:Red 111201 4.2
CVSS:4.0/AV:L/AC:H/AT:P/PR:H/UI:A/VC:L/VI:H/VA:H/SC:H/SI:L/SA:L/CR:L/IR:M/MAV:L/MAC:L/MAT:P/MPR:L/MVC:L/MVI:N/MSC:L/MSI:S/S:P/AU:N/R:U/RE:L 211000 6.9
CVSS:4.0/AV:P/AC:H/AT:P/PR:H/UI:P/VC:H/VI:L/VA:H/SC:L/SI:L/SA:H/E:U/CR:H/IR:H/MAV:A/MAC:H/MAT:P/MPR:H/MUI:A/MVA:N/MSA:N/S:N/R:U/V:C/RE:M/U:Amber 211220 0.7
CVSS:4.0/AV:A/AC:H/AT:P/PR:H/UI:P/VC:L/VI:H/VA:H/SC:H/SI:L/SA:H/E:U/CR:L/IR:H/MAV:L/MAC:H/MAT:N/MPR:H/MUI:N/MVC:H/MVI:L/MSC:H/MSA:S/S:N/AU:N/R:A/U:Clear 111020 5.5
CVSS:4.0/AV:L/AC:H/AT:P/PR:H/UI:P/VC:L/VI:L/VA:L/SC:L/SI:L/SA:H/E:P/CR:M/IR:H/MAC:H/MAT:P/MPR:N/MUI:P/MSC:L/MSI:S/MSA:H/S:N/AU:Y/R:A/RE:H/U:Green 112011 5.0
CVSS:4.0/AV:A/AC:L/AT:P/PR:L/UI:P/VC:L/VI:L/VA:L/SC:H/SI:L/SA:H/E:A/CR:H/IR:L/AR:H/MAV:L/MAC:H/MAT:P/MPR:N/MUI:P/MVC:H/MVA:N/MSI:H/S:N/R:A/V:D/RE:L/U:Red 111100 7.1
CVSS:4.0/AV:L/AC:H/AT:P/PR:L/UI:A/VC:H/VI:L/VA:H/SC:L/SI:H/SA:H/E:U/CR:L/MAV:A/MAC:H/MPR:L/MUI:P/MVI:L/MSC:N/MSI:N/MSA:L/S:N/AU:N/V:D/RE:M/U:Clear 211220 0.7
CVSS:4.0/AV:L/AC:H/AT:P/PR:H/UI:P/VC:L/VI:L/VA:L/SC:H/SI:H/SA:H/E:A/CR:L/IR:M/AR:H/MAV:L/MAC:L/MAT:P/MPR:H/MUI:P/MVC:N/MVI:L/MVA:H/MSC:H/MSI:S/MSA:N/S:P/AU:Y/V:C/U:Amber 211000 6.9
CVSS:4.0/AV:A/AC:H/AT:P/PR:L/UI:A/VC:H/VI:H/VA:H/SC:H/SI:H/SA:H/CR:H/IR:L/AR:L/MAV:P/MAC:L/MPR:H/MUI:A/MVI:L/MVA:L/MSC:N/MSI:S/AU:Y/R:I/V:D/RE:L/U:Amber 211000 6.9
CVSS:4.0/AV:P/AC:H/AT:P/PR:H/UI:A/VC:H/VI:L/VA:L/SC:H/SI:L/SA:H/E:U/IR:H/AR:H/MAV:L/MPR:L/MUI:A/MVA:N/MSC:L/MSI:L/MSA:L/S:N/AU:N/V:C/U:Green 211220 0.7
CVSS:4.0/AV:P/AC:H/AT:P/PR:L/UI:P/VC:H/VI:L/VA:H/SC:H/SI:L/SA:H/E:U/CR:H/IR:H/AR:H/MAV:L/MAC:H/MAT:N/MPR:H/MUI:N/MVC:N/MVI:N/MSC:N/MSI:S/S:P/AU:Y/R:I/V:C/RE:H 111020 5.4
CVSS:4.0/AV:P/AC:L/AT:P/PR:L/UI:A/VC:H/VI:L/VA:H/SC:H/SI:H/SA:L/E:U/CR:M/IR:M/AR:H/MAV:L/MAC:L/MPR:L/MUI:P/MVC:H/MVA:H/MSC:L/MSI:L/S:P/AU:N/R:I/RE:M/U:Amber 211220 0.7
CVSS:4.0/AV:L/AC:L/AT:P/PR:H/UI:A/VC:H/VI:H/VA:H/SC:H/SI:H/SA:H/IR:L/AR:L/MAV:A/MAC:L/MPR:L/MUI:P/MVC:H/MVI:N/MVA:H/MSI:S/MSA:N/R:A/V:C/RE:L/U:Green 211000 6.9
CVSS:4.0/AV:L/AC:H/AT:P/PR:L/UI:A/VC:H/VI:H/VA:L/SC:L/SI:L/SA:H/E:P/CR:L/AR:H/MAV:A/MAC:H/MPR:H/MUI:N/MVC:N/MVI:L/MSI:H/MSA:S/S:N/AU:Y/R:I/RE:M/U:Green 112011 5.0
CVSS:4.0/AV:P/AC:L/AT:P/PR:L/UI:P/VC:H/VI:H/VA:H/SC:L/SI:H/SA:L/E:U/IR:L/MAT:P/MPR:H/MUI:A/MVI:L/MVA:H/MSC:N/MSI:L/MSA:L/S:P/AU:Y/R:U/RE:L/U:Green 211220 0.7
CVSS:4.0/AV:L/AC:H/AT:P/PR:H/UI:A/VC:H/VI:L/VA:L/SC:L/SI:H/SA:L/E:U/CR:H/IR:L/MAV:P/MAT:P/MPR:N/MVA:H/MSI:L/MSA:L/S:N/R:A/RE:L/U:Green 211220 0.7
CVSS:4.0/AV:L/AC:H/AT:P/PR:L/UI:A/VC:H/VI:H/VA:L/SC:H/SI:H/SA:L/E:U/CR:M/IR:M/AR:M/MAV:A/MAC:H/MPR:L/MVC:H/MSC:N/MSI:L/MSA:N/S:P/AU:N/R:I/V:C/RE:L/U:Amber 210221 1.0
CVSS:4.0/AV:L/AC:H/AT:P/PR:H/UI:A/VC:H/VI:H/VA:L/SC:L/SI:H/SA:H/E:U/AR:H/MAC:H/MAT:N/MVC:N/MVI:L/MVA:H/MSC:N/MSI:N/MSA:N/S:N/AU:Y/V:D/RE:H/U:Clear 211220 0.7
CVSS:4.0/AV:A/AC:L/AT:P/PR:L/UI:A/VC:L/VI:H/VA:L/SC:H/SI:L/SA:L/E:U/CR:M/IR:M/AR:H/MAV:A/MAC:L/MUI:N/MVC:N/MVI:N/MVA:H/MSI:S/MSA:H/AU:Y/R:I/V:D/RE:L/U:Clear 111020 5.9
CVSS:4.0/AV:L/AC:H/AT:P/PR:L/UI:P/VC:H/VI:H/VA:H/SC:L/SI:H/SA:H/E:U/IR:L/AR:H/MAV:P/MAC:L/MPR:L/MUI:P/MVC:L/MSC:N/MSI:L/MSA:N/S:P/AU:Y/R:I/U:Green 211220 0.7
CVSS:4.0/AV:P/AC:L/AT:P/PR:H/UI:A/VC:L/VI:L/VA:H/SC:H/SI:L/SA:L/E:U/CR:M/IR:H/AR:M/MAC:H/MAT:N/MPR:L/MUI:N/MVI:H/MSC:L/MSI:N/MSA:L/S:N/AU:N/V:D/RE:H 211220 0.7
CVSS:4.0/AV:P/AC:L/AT:P/PR:L/UI:A/VC:L/VI:H/VA:H/SC:H/SI:L/SA:L/E:A/CR:H/IR:L/AR:H/MAV:A/MAC:H/MPR:L/MUI:N/MVC:H/MVI:L/MVA:N/MSC:H/MSI:S/MSA:L/S:P/AU:N/R:I/V:C/RE:M/U:Red 111000 8.6
CVSS:4.0/AV:L/AC:H/AT:P/PR:L/UI:A/VC:L/VI:H/VA:H/SC:L/SI:L/SA:H/E:U/CR:L/AR:L/MAV:P/MAC:L/MAT:N/MPR:N/MVA:H/MSC:N/MSI:S/S:N/AU:N/R:I/RE:M/U:Amber 201020 5.8
CVSS:4.0/AV:P/AC:H/AT:P/PR:L/UI:P/VC:L/VI:L/VA:L/SC:L/SI:L/SA:L/E:U/CR:L/IR:L/AR:H/MAV:A/MPR:H/MUI:A/MVC:H/MVI:H/MVA:N/MSI:N/MSA:L/AU:Y/R:I/RE:H/U:Amber 210221 0.7
CVSS:4.0/AV:P/AC:H/AT:P/PR:L/UI:P/VC:L/VI:H/VA:L/SC:H/SI:H/SA:L/E:P/CR:H/IR:L/AR:H/MAV:A/MAC:L/MPR:N/MUI:A/MVC:N/MVI:N/MVA:L/MSI:S/MSA:L/R:A 112011 5.0
CVSS:4.0/AV:A/AC:H/AT:P/PR:L/UI:A/VC:H/VI:L/VA:H/SC:H/SI:H/SA:H/E:A/CR:H/IR:L/MAC:H/MPR:N/MUI:A/MVC:L/MVI:N/MVA:H/S:N/AU:N/V:C/RE:H/U:Red 111100 7.1
CVSS:4.0/AV:L/AC:H/AT:P/PR:L/UI:P/VC:H/VI:H/VA:H/SC:L/SI:H/SA:H/CR:L/IR:H/AR:M/MAV:L/MAT:N/MPR:N/MUI:N/MVC:N/MVI:H/MVA:H/MSI:S/MSA:H/S:N/AU:N/R:U/V:C/RE:H/U:Green 111000 8.6
CVSS:4.0/AV:L/AC:L/AT:P/PR:H/UI:P/VC:L/VI:H/VA:L/SC:L/SI:H/SA:H/E:U/CR:L/IR:L/MAV:L/MAT:P/MPR:N/MUI:N/MVI:N/MVA:H/MSC:H/MSI:L/MSA:S/S:N/AU:Y/R:I/U:Green 111020 5.8
CVSS:4.0/AV:P/AC:H/AT:P/PR:L/UI:A/VC:L/VI:H/VA:H/SC:H/SI:H/SA:H/E:U/AR:M/MAV:P/MAC:L/MPR:H/MUI:P/MVC:H/MVI:L/MVA:L/MSC:N/MSI:N/MSA:N/S:P/R:A/V:D/RE:H/U:Red 211220 0.7
CVSS:4.0/AV:P/AC:L/AT:P/PR:L/UI:A/VC:H/VI:H/VA:H/SC:L/SI:H/SA:H/E:U/CR:M/AR:L/MAV:A/MAC:H/MPR:N/MVC:L/MVA:H/MSC:L/MSI:N/MSA:S/S:N/AU:N/R:A/RE:H 111020 5.5
CVSS:4.0/AV:L/AC:L/AT:P/PR:H/UI:P/VC:L/VI:H/VA:H/SC:L/SI:L/SA:H/E:A/IR:M/AR:M/MAV:N/MAC:L/MPR:H/MUI:A/MVC:L/MVI:H/MVA:H/MSI:L/MSA:N/S:N/AU:N/V:D/U:Amber 111201 4.4
CVSS:4.0/AV:A/AC:L/AT:P/PR:H/UI:A/VC:H/VI:L/VA:H/SC:L/SI:H/SA:H/E:U/IR:H/MAV:L/MAC:H/MAT:N/MPR:H/MUI:P/MVC:L/MVI:H/MVA:N/MSI:L/MSA:N/V:C 211220 0.7
CVSS:4.0/AV:L/AC:L/AT:P/PR:L/UI:P/VC:L/VI:H/VA:H/SC:H/SI:L/SA:H/E:U/IR:M/MAV:L/MAC:H/MPR:L/MUI:A/MVC:H/MVI:N/MVA:H/MSC:N/MSI:L/MSA:N/S:P/AU:Y/RE:L/U:Amber 211220 0.7
CVSS:4.0/AV:A/AC:H/AT:P/PR:L/UI:A/VC:H/VI:H/VA:H/SC:L/SI:H/SA:L/E:U/CR:L/IR:M/AR:M/MAV:L/MAT:P/MUI:P/MVC:H/MVA:N/MSI:L/MSA:L/R:I/U:Red 210221 0.7
CVSS:4.0/AV:P/AC:L/AT:P/PR:H/UI:A/VC:H/VI:H/VA:L/SC:L/SI:L/SA:H/E:A/CR:M/IR:H/AR:M/MAV:L/MAC:H/MVC:N/MVI:H/MVA:N/MSA:S/R:A/V:C/RE:L/U:Clear 211000 6.9
```

Just documenting my progress...

**Comment by xaldama** [comment]
I added a selenium test in my branch to compare scores with First.org (not committed).
The differences that remains after this change is because javascript calculation limitation.
image

This is really below 6.5 and it should be rounded to 0.6

**Comment by YanWittmann** [comment]
I have found the cause for the imprecision, I think.

Please view the rounding function they use in the JS:
https://github.com/RedHatProductSecurity/cvss-v4-calculator/blob/d1eafe06859e6610600f772ed98502bc1cd63526/cvss40.js#L24

```js
/**
 * Rounds a number to a specified number of decimal places using the "Round Half Up" method.
 *
 * This function shifts the decimal point to the right by the specified number of decimal places,
 * rounds the shifted value to the nearest integer using the "Round Half Up" method, and then shifts
 * the decimal point back to its original position. The final result is returned as a floating-point
 * number with the desired number of decimal places.
 *
 * The "Round Half Up" method rounds a number to the nearest neighbor, rounding .5 away from zero.
 *
 * @param {number} value - The number to be rounded.
 * @return {number} - The number rounded to one decimal place, using an additive adjustment value (EPSILON) to avoid floating-point misrepresentations of values.
 * For example, 8.6 - 7.15 will return 1.4499999999999993 rather than 1.45. When rounded to one decimal place, this will incorrectly produce 1.4, instead of 1.5 (the correct result).
 *  The specific EPSILON value is based on interval machine epsilon value for single-precision floating point decimals. See https://en.wikipedia.org/wiki/Machine_epsilon. 
 *
 * @example
 * roundToDecimalPlaces(4.945833333333333);   // returns 4.9
 * roundToDecimalPlaces(4.25);                // returns 4.3
 * roundToDecimalPlaces(1.4499999999999993); // returns 1.5
 */
function roundToDecimalPlaces(value) {
    const EPSILON = Math.pow(10, -6);
    return Math.round((value + EPSILON) * 10) / 10;
}
```

The only change I had to make to the Java implementation consistent with the JS version:

```java
private final static MathContext ROUNDING_MATH_CONTEXT = new MathContext(17, RoundingMode.HALF_UP);
private final static double ROUNDING_EPSILON = Math.pow(10, -6);

private String javaScriptToFixed(double number, int fractionDigits) {
    // - set scale to round half up, which is the behavior in JS's toFixed.
    // - additive adjustment value (ROUNDING_EPSILON) to avoid floating-point misrepresentations of values. See https://en.wikipedia.org/wiki/Machine_epsilon.
    return new BigDecimal(number + ROUNDING_EPSILON, ROUNDING_MATH_CONTEXT)
            .setScale(fractionDigits, RoundingMode.HALF_UP)
            .toPlainString()
            .replace(",", ".");
}
```

It now calculates all those vectors correctly I mentioned above, in addition to all others that are unchanged.

---

Sorry, I just noticed your comment you wrote in the meantime after finishing mine.
I think my comment still applies and the cause for the "rounding error" is their special rounding function that intentionally adds a tiny machine error margin to accommodate for prior imprecisions.

Please let me know if this change works for you, rolling back to the initial state and applying my new rounding function.

**Comment by YanWittmann** [comment]
If so, I can simply create a new PR with my changes I have on another branch right now.

**Comment by YanWittmann** [comment]
I just applied these changes to the https://www.npmjs.com/package/ae-cvss-calculator and they now calculate the values correctly:

https://github.com/org-metaeffekt/metaeffekt-universal-cvss-calculator/blob/cde3924988e8088fadfc336ffa04d6cd23e474e1/ae-cvss-calculator/src/cvss4p0/Cvss4P0.ts#L145

```js
// ...
    if (adjustedOriginalMacroVectorScore < 0) {
        return 0.0;
    } else if (adjustedOriginalMacroVectorScore > 10) {
        return 10.0;
    } else {
        return this.roundToDecimalPlaces(adjustedOriginalMacroVectorScore);
    }
}

private readonly ROUNDING_EPSILON = Math.pow(10, -6);

private roundToDecimalPlaces(value: number) {
    return Math.round((value + this.ROUNDING_EPSILON) * 10) / 10;
}
```

**Comment by YanWittmann** [comment]
I have opened a PR here that implements my changes: https://github.com/org-metaeffekt/metaeffekt-core/pull/164
If you wouldn't mind, I would like to ask you to check it out and see if it fixes your issues with the calculation. For me, it does correctly calculate all vectors the same way as the reference implementation.

**Comment by karsten-klein** [comment]
Thanks you @xaldama for your insights and bug report. With Yan's changes on [#164](https://github.com/org-metaeffekt/metaeffekt-core/pull/164) we regard the issue as fixed and will close the initial PR.

Your input is highly appreciated. If you have further concerns or incorrect boundary cases, let us know.

**Pull request closed without merging**
